name: CP-DP APIs Performance

on:
  workflow_dispatch:
    inputs:
      perf-env:
        type: string
        description: Select the perf environment
        required: true
        default: 'pre24-green'

    
jobs:
  cp-dp-concurrent-run:
    runs-on: ubuntu-latest
    environment: pre24-green
    container:
      image: octoperf/jmeter-standard
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          # http-proxy: "http://proxy-us.intel.com:911"
          
      - name: Install AWS CLI
        run: |
          apt-get update
          apt-get install -y awscli

      - name: Install kubectl
        run: |
          curl -LO https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.15/2023-01-11/bin/linux/amd64/kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin/
          kubectl version --client    
        
      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        
      - name: Get node CPU utilization
        run: |
          export http_proxy=http://proxy-us.intel.com:911
          export https_proxy=http://proxy-us.intel.com:911
          export KUBECONFIG=/github/home/.kube/config
          sleep 3600
          kubectl get ns
          kubectl get pods
          kubectl top nodes
          
      - name: Execute JMeter Script
        run: |        
          $JMETER_HOME/bin/jmeter -h
