name: Jmeter

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Message
        run: 
          lscpu
          free -m
          hostnamectl
          echo Welcome to start JMeter!

      - name: Run Sample JMeter Test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
