name: Tenant CLI

on:
  workflow_dispatch:
    inputs:
      iterations:
        type: string
        description: Number of iterations to run
        required: true
        default: '10'
        
jobs:
  run-cli-operations:
    runs-on: trustauthorityctl

    steps:
      - name: Get Host Details
        run: |
          lscpu
          free -m
          hostnamectl
          who
          echo Welcome to Tenant CLI Host!

      - name: Run Test CLI Command
        run: |
          pwd
          source ~/.bash_profile
          trustauthorityctl list user

      - name: Run CLI Script
        run: |
          /home/vinitkum/tenantctl_ga.sh ${{ github.event.inputs.iterations }}
      
      - name: Upload Results to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cli-results
          path: /home/vinitkum/results.html


  upload-reports-to-webserver:
    runs-on: trustauthorityctl
    needs: [run-cli-operations]

    steps:
      - name: Copy Reports to Webserver
        run: |
          scp /home/vinitkum/results.html 10.80.245.171:/var/www/html/latest
          echo "Latest Results are available at http://vinit-nfs.fm.intel.com/latest/results.html "
