name: Tenant CLI

on:
  workflow_dispatch:

jobs:
  run-cli-operations:
    runs-on: trustauthorityctl

    steps:
      - name: Print Message
        run: |
          lscpu
          free -m
          hostnamectl
          who
          echo Welcome to Tenant CLI Host!

      - name: Run Sample CLI Command
        run: |
          pwd
          source ~/.bash_profile
          trustauthorityctl list user

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: cli-results
          path: /home/vinitkum/results.txt
